-- TRIGGER RESPONSÁVEL POR ATUALIZAR AUTOMATICAMENTE O STATUS DO VEÍCULO PARA 'LOCADO'
-- SEMPRE QUE UMA NOVA LOCAÇÃO FOR REGISTRADA NA TABELA 'LOCACOES.
DELIMITER $$

CREATE TRIGGER tr_atualiza_status_veiculo
AFTER INSERT ON locacoes
FOR EACH ROW
BEGIN
    UPDATE veiculos
    SET status = 'Locado'
    WHERE id_veiculo = NEW.id_veiculo;
END$$

DELIMITER ;


-- TRIGGER RESPONSÁVEL POR ATUALIZAR AUTOMATICAMENTE O STATUS DO VEÍCULO PARA "DISPONÍVEL"
-- SEMPRE QUE UMA LOCAÇÃO TIVER O STATUS ALTERADO PARA "FINALIZADA" OU "CANCELADA".
DELIMITER $$

CREATE TRIGGER tr_libera_veiculo
AFTER UPDATE ON locacoes
FOR EACH ROW
BEGIN
    IF NEW.status IN ('Finalizada', 'Cancelada') THEN
        UPDATE veiculos
        SET status = 'Disponível'
        WHERE id_veiculo = NEW.id_veiculo;
    END IF;
END$$

DELIMITER ;